In [1]:
import torch
import matplotlib.pyplot as plt
import json
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format
import glob 

RESULTS = "./results_gen/computed_metrics"

# Patch normalized field

In [2]:
fn = glob.glob(f"{RESULTS}/**.json")

result_list_patched = []
for filename in fn:
    with open(filename,"r") as f:
        result_list = json.load(f)
    if "_normalized" in filename:
        for r in result_list: 
            r["normalized"] = "Normalized" 
            result_list_patched.append(r)
    else: 
        for r in result_list: 
            r["normalized"] = "Original" 
            result_list_patched.append(r)

df = pd.DataFrame(result_list_patched)

df["1-NN-CD-acc"] = df["1-NN-CD-acc"] * 100
df["1-NN-EMD-acc"] = df["1-NN-EMD-acc"] * 100
df["normalized"] = df["normalized"].astype(str)

df.head()

,1-NN-CD-acc_t,1-NN-CD-acc_f,1-NN-CD-acc,1-NN-EMD-acc_t,1-NN-EMD-acc_f,1-NN-EMD-acc,model,cate,normalized,run
0,0.63,0.72,67.50,0.82,0.67,74.50,PointFlow,airplane,Original,0
1,0.67,0.65,66.00,0.72,0.49,60.50,PointFlow,airplane,Original,1
2,0.64,0.67,65.50,0.75,0.56,65.50,PointFlow,airplane,Original,2
3,0.71,0.76,73.50,0.76,0.65,70.50,PointFlow,airplane,Original,3
4,0.66,0.77,71.50,0.83,0.58,70.50,PointFlow,airplane,Original,4

In [3]:
len(result_list_patched)

90

In [4]:
dg = df[["1-NN-CD-acc","1-NN-EMD-acc","model","cate","normalized"]].groupby(["normalized","model","cate",]).agg(["mean","std"])
dg.unstack().swaplevel(1,2,axis=1).swaplevel(0,1,axis=1).sort_index(axis=1)

cate                    airplane                                car       \
                     1-NN-CD-acc      1-NN-EMD-acc      1-NN-CD-acc
                            mean  std         mean  std        mean  std
normalized model
Normalized PointFlow       79.10 4.75        73.90 4.64       54.60 5.08
           VAE             86.10 0.42        95.90 1.52       66.80 2.95
           VAEScaled       85.50 1.27        85.90 2.16       70.10 1.34
Original   PointFlow       68.80 3.53        68.30 5.40       58.90 3.70
           VAE             76.10 1.52        89.20 0.76       60.50 1.50
           VAEScaled      100.00 0.00       100.00 0.00       99.00 0.00

cate                                         chair
                     1-NN-EMD-acc      1-NN-CD-acc      1-NN-EMD-acc
                             mean  std        mean  std         mean  std
normalized model
Normalized PointFlow        54.10 5.26       58.30 1.89        57.20 3.56
           VAE              78.70 1.35       64.50 2.18        72.90 2.82
           VAEScaled        77.30 1.35       64.50 1.80        70.40 1.29
Original   PointFlow        56.90 1.34       57.50 1.80        54.10 2.43
           VAE              73.10 1.98       57.60 0.82        65.30 2.36
           VAEScaled        99.00 0.00      100.00 0.00       100.00 0.00